name: Generate and Publish Documentation

on:
  push:
    branches:
      - master

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Doxygen
        run: sudo apt-get install doxygen graphviz -y  

      - name: Generate Documentation
        run: doxygen Doxyfile  
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
            
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html  
