name: build and run 
on: [push]
jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y cmake
      - run: g++ main.cpp my_add.cpp -o main
      - run: mkdir build && cmake -B build -S . && cmake --build build 
      - run: ./build/main 10 20
