name: build and run 
on: [push]
jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y cmake
      - run: g++ main.cpp my_add.cpp -o main
      # - run: mkdir build && cmake -B build -S . && cmake --build build 
      - run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . 

      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: binaries
      #     path:
      #       build/main
      #       build/tests
      - uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: |
            build/main
            build/tests
            build/my_bench


  tests:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: binaries
      - run: chmod +x tests && ./tests

  run:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: binaries
      - run: chmod +x main && ./main 3 10
 
  bench:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: binaries
      - run: chmod +x my_bench && ./my_bench

